[workspace]
members = [
    ".", 
    "libs/image", "libs/myanimelist",
    "libs/pixiv"
]

[[bin]]
name = "nenechi-cli"

[package]
name = "nenechi-cli"
version = "0.2.15"
edition = "2024"

[dependencies]
nenechi-pixiv = { path = "libs/pixiv" }
nenechi-image = { path = "libs/image" }
nenechi-myanimelist = { path = "libs/myanimelist" }
clap = { version = "4.5.41", features = ["derive"] }
log = "0.4"
fern = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_with = { version = "3", features = ["base64"] }
walkdir = "2.3"
diesel = { version = "2.2.0", features = ["sqlite", "serde_json", "r2d2"] }
diesel_migrations = "2.2.0"
serde_json = "1.0.141"
glob = "0.3.2"
regex = "1.11"
uuid = { version = "1.8.0", features = ["v4", "v7"] }
serial_test = "3.2.0"
dotenvy = "0.15.7"
reqwest = { version = "0.13.4", features = ["blocking", "query", "json"] }
quick-xml = { version = "0.41.0", features = ["serialize"] }
chrono = "0.4.45"

[dev-dependencies]
tempfile = "3.20"
