[workspace]
members = [
    ".", 
    "libs/image",
    "libs/pixiv"
]

[[bin]]
name = "nenechi-cli"

[package]
name = "nenechi-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
nenechi-pixiv = { path = "libs/pixiv" }
nenechi-image = { path = "libs/image" }
clap = { version = "4.5.41", features = ["derive"] }
log = "0.4"
fern = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
walkdir = "2.3"
diesel = { version = "2.2.0", features = ["sqlite", "serde_json", "r2d2"] }
diesel_migrations = "2.2.0"
serde_json = "1.0.141"
glob = "0.3.2"
uuid = { version = "1.8.0", features = ["v4", "v7"] }
serial_test = "3.2.0"
