[workspace]
members = [
    ".", 
    "libs/image",
    "libs/pixiv"
]

[[bin]]
name = "nenechi-cli"

[package]
name = "nenechi-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
nenechi-pixiv = { path = "libs/pixiv" }
nenechi-image = { path = "libs/image" }
clap = { version = "4.5.41", features = ["derive"] }
log = "0.4"
log4rs = "1.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
walkdir = "2.3"
