logging:
  # Nivel de log: trace, debug, info, warn, error.
  # También se puede sobreescribir con la variable de entorno RUST_LOG.
  level: "info"
  # Lista de salidas activas. Opciones: "console", "file".
  output: "console"
  # Ruta del fichero de logs.
  # Solo funcionara si el output es "file"
  file: "nenechi-cli.log"
