logging:
  # Nivel de log: trace, debug, info, warn, error.
  # También se puede sobreescribir con la variable de entorno RUST_LOG.
  level: info
  # Lista de salidas activas. Opciones: "console", "file".
  output: console
  # Ruta del fichero de logs.
  # Solo funcionara si el output es "file"
  file: nenechi-cli.log

database:
  # Ruta del fichero de la base de datos
  file: nenechi-cli.db

wallpapers:
  # Configuracion para ordenar y clasificar los wallpapers
  tidy:
    # Ruta al directorio donde estan todos los wallpapers
    all_directory: wallpapers/all
    # Ruta al directorios donde se organizaran por aspect ratio
    # Por ejemplo: portrait (mobile), landscape (desktop) o square
    aspect_ratio_directory: wallpapers/by-aspect-ratio
    # Ruta al directorios donde se organizaran por tags de Pixiv
    # si estan disponibles
    tags_directory: wallpapers/by-tags
