logging:
  # Nivel de log: trace, debug, info, warn, error.
  level: info
  # Los logs se escriben simultáneamente en la consola y en este fichero.
  file: ~/.local/state/nenechi/logs/nenechi.log

database:
  # Ruta del fichero de la base de datos
  file: ~/.local/share/nenechi/nenechi-cli.db

myanimelist:
  # Client ID de la API v2 de MyAnimeList.
  api_key: your-client-id

jdownloader:
  api_base_url: http://localhost:3128
