logging:
  # Nivel de log: trace, debug, info, warn, error.
  level: info
  # Los logs se escriben simultáneamente en la consola y en este fichero.
  file: /var/log/nenechi.log

database:
  # Ruta del fichero de la base de datos
  file: ~/.local/nenechi/nenechi-cli.db
